[colors.primary]
background = '#000000'
foreground = '#B3B1AD'

[colors.normal]
black   = '#01060E'
red     = '#EA6C73'
green   = '#91B362'
yellow  = '#F9AF4F'
blue    = '#53BDFA'
magenta = '#FAE994'
cyan    = '#90E1C6'
white   = '#C7C7C7'

[colors.bright]
black   = '#686868'
red     = '#F07178'
green   = '#C2D94C'
yellow  = '#FFB454'
blue    = '#59C2FF'
magenta = '#FFEE99'
cyan    = '#95E6CB'
white   = '#FFFFFF'

[font]
normal = { family = "MesloLGS Nerd Font", style = "Regular"}
bold = { family = "MesloLGS Nerd Font", style = "Bold"}
italic = { family = "MesloLGS Nerd Font", style = "Italic"}
bold_italic = { family = "MesloLGS Nerd Font", style = "Bold Italic"}
size = 12

[window]
decorations = "Transparent"
opacity = 0.5
